spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: password
    url: jdbc:h2:mem:testdb
    username: sa
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

batch:
  configuration:
    email: info@thinktech.com
    message: "this email is sent to all the persons"

